<?php

/**
 * Implements hook_block_info().
 */
 
function siteinfo_block_info() {
  // This example comes from node.module.
  $blocks['siteinfo'] = array(
    'info' => t('Site Information'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}
 
 /**
 * Implements hook_block_view().
 */
function siteinfo_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'siteinfo':
      $block['subject'] = t('Site Detail');
	  //$form = drupal_get_form('siteinfo_detailform');
     // $block['content'] = drupal_render($form);
	 $block['content'] = siteinfo_details();
      break;
  }
  return $block;
}


/**
 * Implements siteinfo_details function().
 */
function siteinfo_details() {
	
	global $databases;	
	$db_name = $databases['default']['default']['database'];
	$db_driver = $databases['default']['default']['driver'];

	$site_name = variable_get('site_name');
	$default_theme = variable_get('theme_default');
	$admin_theme = variable_get('admin_theme');
	$file_temporary_path = variable_get('file_temporary_path');
	$install_time = variable_get('install_time');
	$cron_last_run = variable_get('cron_last');
	$clean_url = variable_get('clean_url');

	$install_date = format_date($install_time, 'dateonly');
	$cron_run = format_date($cron_last_run, 'dateonly');
	$cln_url = isset($clean_url) ? "Yes" : "No";

	$php_version = phpversion();
	$roles = user_roles(true);
	$count_role = sizeof($roles);

	$user_list = entity_load('user')
	$number_user = count($user_list);

	$cont_type = node_type_get_types();
	$number_cont_type = sizeof($cont_type);

	$mod_list = module_list($refresh = FALSE, $bootstrap_refresh = FALSE, $sort = FALSE, $fixed_list = NULL);
	$number_mod = count($mod_list);
	$drupal_version = VERSION;
  
    
				 
	$header = array(
        array('data' => "Site Details", 'colspan' => 2));
	$rows['site_name'] = array('data' => array("Site Name : ", $site_name)); 
	$rows['drupal_version'] = array("Drupal Version : ", $drupal_version); 
	$rows['install_date'] = array("Install date : ", $install_date); 
	$rows['cron_run'] = array("Last cron run : ", $cron_run); 
	$rows['cln_url'] = array("Clean URL : ", $cln_url); 
	$rows['file_temporary_path'] = array("File temporary path : ", $file_temporary_path); 
	
	$rows['php_version'] = array("Php version : ", $php_version); 
	$rows['db_driver'] = array("Database driver : ", $db_driver); 
	$rows['db_name'] = array("Database Name : ", $db_name); 
	$rows['default_theme'] = array("Default theme : ", $default_theme); 
	$rows['admin_theme'] = array("Admin theme : ", $admin_theme); 
	$rows['count_role'] = array("Total role : ", $count_role);
	
	$rows['number_user'] = array("Total users : ", $number_user); 
	$rows['number_cont_type'] = array("Total content type : ", $number_cont_type); 
	$rows['number_mod'] = array("Enables Module : ", $number_mod); 
	
	$output = theme('table', 
           array('header' => $header, 
                  'rows' => $rows));
	
	
	$lim = 0;
	foreach ($cont_type as $key => $value) {
		$mod_col[$lim][0] = $value->name;
		
		$query = new EntityFieldQuery();
		$query->entityCondition('entity_type', 'node') // grab nodes
		->entityCondition('bundle', $key) // filter by blog type
		->propertyCondition('status', 1) // filter by published
		->count(); // count

		$result = $query->execute();
		$mod_col[$lim][1] = $result;
		$lim++;
	}
	

	$lim = 0;
	foreach ($roles as $key) {
		if (!isset($mod_col[$lim][0])) {
			$mod_col[$lim][1] = "";
		}
		$mod_col[$lim][2] = $key;
		$lim++;
	}
	
	
	$lim = 0;
	foreach ($mod_list as $key) {
		if (!isset($mod_col[$lim][0])) {
			$mod_col[$lim][0] = "";
		}
		if (!isset($mod_col[$lim][1])) {
			$mod_col[$lim][1] = "";
		}
		if (!isset($mod_col[$lim][2])) {
			$mod_col[$lim][2] = "";
		}
		$mod_col[$lim][3] = $key;
		$lim++;
	}
	

	$lim = 0;
	foreach ($user_list as $key => $value) {

		if (!isset($mod_col[$lim][0])) {
			$mod_col[$lim][0] = "";
		}
		if (!isset($mod_col[$lim][1])) {
			$mod_col[$lim][1] = "";
		}
		if (!isset($mod_col[$lim][2])) {
			$mod_col[$lim][2] = "";
		}
		if (!isset($mod_col[$lim][3])) {
			$mod_col[$lim][3] = "";
		}
		if (empty($value->name)) {
			
			$mod_col[$lim][4] = "Anonymous";
		    
		} else {	
			$mod_col[$lim][4] = $value->name; 
		}
		$lim++;
	}
	
	$lim = 0;
	foreach ($mod_col as $key => $value) {
		if (!isset($mod_col[$lim][4])) {
			$mod_col[$lim][4] = "";
		}
		$lim++;
	}
	
	$header = array('Content Type', 'Node', 'Roles', 'Modules', 'Users');
	$output .= theme('table', 
        array('header' => $header, 
            'rows' => $mod_col));
	
return $output;

}
